prjHosNav/Controllers/HomeController.cs
using prjHosNav.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjHosNav.ViewModel;

namespace prjHosNav.Controllers
{
    public class HomeController : Controller
    {
        
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

        //門診後台管理
        COutpatientFactory COF = new COutpatientFactory();
        public ActionResult outpatient()
        {
            return View();
        }

        public JsonResult List()
        {
            return Json(COF.queryAll(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add(COutpatient op)
        {
            return Json(COF.create(op), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetById(int id)
        {
            var Outpatient = COF.queryAll().Find(x => x.oid.Equals(id));
            return Json(Outpatient, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update(COutpatient op)
        {
            return Json(COF.update(op), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(int id)
        {
            return Json(COF.delete(id), JsonRequestBehavior.AllowGet);
        }

        //症狀查詢後台管理
        CSearchFactory CSF = new CSearchFactory();
        public ActionResult Search()
        {
            return View();
        }

        public JsonResult SearchList()
        {
            return Json(CSF.queryAll(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult SearchAdd(CSearch op)
        {
            return Json(CSF.create(op), JsonRequestBehavior.AllowGet);
        }

        public JsonResult SearchGetById(int id)
        {
            var Outpatient = CSF.queryAll().Find(x => x.SId.Equals(id));
            return Json(Outpatient, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SearchUpdate(CSearch op)
        {
            return Json(CSF.update(op), JsonRequestBehavior.AllowGet);
        }

        public JsonResult SearchDelete(int id)
        {
            return Json(CSF.delete(id), JsonRequestBehavior.AllowGet);
        }

        //會員登入系統
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session[CDictionary.SK_LOGINED_USER] = null;
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Login(CLoginViewModel p)
        {
            CMember cust = new CMemberFactory().queryByEmail(p.txtEmail);
            if (cust != null && cust.mPassword.Equals(p.txtPassword))
            {
                Session[CDictionary.SK_LOGINED_USER] = cust;
                return RedirectToAction("Index");
            }
            TempData["message"] = "帳號密碼有誤，請重新登入";
            return RedirectToAction("Index");
        }

        public ActionResult 註冊成功()
        {
            return View();
        }

    }
}

prjHosNav/Controllers/MedicineController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjHosNav.Models;

namespace prjHosNav.Controllers
{
    public class MedicineController : Controller
    {
        
        public ActionResult myBoxSave()
        {
            if(Session[CDictionary.SK_LOGINED_USER] != null)
            {
                CMyMedicineBoxDetail x = new CMyMedicineBoxDetail();
                x.fChName = Request.Form["fChName"];
                x.fImagePath = Request.Form["fImagePath"];
                x.fDayOfUse = Request.Form["fDayOfUse"];
                x.fQuantityUse = Request.Form["fQuantityUse"];
                x.MId = (Session[CDictionary.SK_LOGINED_USER] as CMember).mId.ToString();
                (new CMyMedicineBoxFactory()).create(x);
                return RedirectToAction("myBox");
            }
            else
            {
                TempData["message"] = "尚未登入";
                return RedirectToAction("List", "Home");
            }                       
        }


        public ActionResult myBoxDelete(int id)
        {
            int userId = (Session[CDictionary.SK_LOGINED_USER] as CMember).mId;
            (new CMyMedicineBoxFactory()).delete(id,userId);
            return RedirectToAction("mybox");
        }
        public ActionResult myBoxEdit(int id)
        {
            CMyMedicineBoxDetail data = (new CMyMedicineBoxFactory()).queryById(id);
            if (data == null)
                return RedirectToAction("myBox");
            return View(data);
        }
        [HttpPost]
        public ActionResult myBoxEdit(CMyMedicineBoxDetail p)
        {
            p.MId =(Session[CDictionary.SK_LOGINED_USER] as CMember).mId.ToString();
            (new CMyMedicineBoxFactory()).update(p);
            return RedirectToAction("myBox");
        }

        public ActionResult myBoxCreate(int id)
        {
            if (Session[CDictionary.SK_LOGINED_USER] == null)
            {
                TempData["message"] = "尚未登入";
                return RedirectToAction("Index", "Home");
            }
            CMedicineDetail data = (new CMedicineFactory()).queryById(id);
            if (data == null)
                return RedirectToAction("List");
            return View(data);
           
        }

        public ActionResult myBox()
        {
            if (Session[CDictionary.SK_LOGINED_USER] == null)
            {
                TempData["message"] = "尚未登入";
                return RedirectToAction("Index", "Home");
            }
            int userId = (Session[CDictionary.SK_LOGINED_USER] as CMember).mId;
            List<CMyMedicineBoxDetail> data = null;            
            data = (new CMyMedicineBoxFactory()).queryByMId(userId);
            return View(data);
        }

        // GET: Medicine
        public ActionResult List()
        {
            List<CMedicineDetail> data = null;
            if (string.IsNullOrEmpty(Request.Form["txtKeyword"]))
                data = (new CMedicineFactory()).queryAll();
            else
                data = (new CMedicineFactory()).queryByKeyword(Request.Form["txtKeyword"]);
            string a = Request.Form["txtKeyword"];
            ViewBag.Ans = a;
            Console.WriteLine(data);
            return View(data);

        }

        public ActionResult ListAdmin()
        {
            List<CMedicineDetail> data = null;
            if (string.IsNullOrEmpty(Request.Form["txtKeyword"]))
                data = (new CMedicineFactory()).queryAll();
            else
                data = (new CMedicineFactory()).queryByKeyword(Request.Form["txtKeyword"]);
            return View(data);
        }


        public ActionResult Edit(int id)
        {
            CMedicineDetail data = (new CMedicineFactory()).queryById(id);
            if (data == null)
                return RedirectToAction("List");
            return View(data);
        }

        [HttpPost]
        public ActionResult Edit(CMedicineDetail p)
        {
            (new CMedicineFactory()).update(p);
            return RedirectToAction("ListAdmin");
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Delete(int id)
        {
            (new CMedicineFactory()).delete(id);
            return RedirectToAction("ListAdmin");
        }

        [HttpPost]
        public ActionResult Save(HttpPostedFileBase fImagePath)
        {
            var fileName = fImagePath.FileName;
            var filePath = Server.MapPath("~/img/MImg/");
            //var filePath = Server.MapPath(string.Format("~/{0}", "File"));
            fImagePath.SaveAs(Path.Combine(filePath, fileName));

            CMedicineDetail x = new CMedicineDetail();
            x.fChName = Request.Form["fChName"];
            x.fEnName = Request.Form["fEnName"];
            x.fSymptoms = Request.Form["fSymptoms"];
            x.fCaution = Request.Form["fCaution"];
            x.fImagePath = fImagePath.FileName;

            (new CMedicineFactory()).create(x);
            return RedirectToAction("ListAdmin");
        }

    }
}

prjHosNav/Controllers/OutpatientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjHosNav.Models;

namespace prjHosNav.Controllers
{
    public class OutpatientController : Controller
    {
        // GET: Outpatient
        public ActionResult List()
        {
            List<CHospital> data = new CHospitalFactory().queryAll();
            return View(data);
        }

        public ActionResult 診間(string id)
        {
            List<COutpatient> o = (new COutpatientFactory()).queryByhId(id);
            return View(o);
        }

        public ActionResult location(int id)
        {
            return View();
        }
    }
}

prjHosNav/Controllers/ReturnController.cs
using prjHosNav.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjHosNav.ViewModel;

namespace prjHosNav.Controllers
{
    public class ReturnController : Controller
    {
        CReturnFactory CRF = new CReturnFactory();
        // GET: Return
        public ActionResult Return()
        {
            if (Session[CDictionary.SK_LOGINED_USER] == null)
            {
                TempData["message"] = "尚未登入";
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        public JsonResult List()
        {
            return Json(CRF.queryAll(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Add(CReturn op)
        {
            return Json(CRF.create(op), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetById(int id)
        {
            var HosReturn = CRF.queryAll().Find(x => x.RId.Equals(id));
            return Json(HosReturn, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetByMId(int id)
        {
            var HosReturn = new CReturnFactory().queryByMId(id);
            return Json(HosReturn, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Update(CReturn op)
        {
            return Json(CRF.update(op), JsonRequestBehavior.AllowGet);
        }

        public JsonResult Delete(int id)
        {
            return Json(CRF.delete(id), JsonRequestBehavior.AllowGet);
        }
    }
}

prjHosNav/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prjHosNav.Models;

namespace prjHosNav.Controllers 
{
    public class SearchController : Controller
    {
        // GET: Search
        public ActionResult List()
        {
            List<CSearch> data = null;
            if (string.IsNullOrEmpty(Request.Form["txtKeyword"]))
                data = (new CSearchFactory()).queryAll();
            else
            {
                data = (new CSearchFactory()).queryByKeyword(Request.Form["txtKeyword"]);
                string a = Request.Form["txtKeyword"];
                ViewBag.Ans = a;
                Console.WriteLine(data);
            }
            return View(data);
        }

        public ActionResult Search2()
        {
            return View();
        }

    }
}

prjHosNav/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>首頁</title>

    <style>
        header {
            background: url(/img/2472884.svg);
            background-repeat: no-repeat;
            background-position: center center;
            background-size: cover;
        }

        .reveal .box {
            position: relative;
        }

        .spacer {
            aspect-ratio: 960/300;
            width: 100%;
            background-repeat: no-repeat;
            background-position: center;
            background-size: cover;
        }

        .layer1 {
            background-image: url("/img/home/layer1.svg");
        }

        .section {
            background: #e8fbff;
        }

        .space {
            height: 200px;
        }

        .section video {
            object-fit: cover;
            width: 100%;
            height: 100%;
        }

        .ul-home {
            list-style-type: none;
            padding: 0;
        }

            .ul-home li {
                cursor: pointer;
                margin: 45px;
                padding: 16px;
                border-radius: 8px;
                background-color: #fff;
                box-shadow: 0 10px 70px 0 rgb(103 151 255 / 22%), 0 15px 105px 0 rgb(103 151 255 / 22%);
                transition: all 1s ease-out;
            }

                .ul-home li:hover {
                    opacity: 1;
                    box-shadow: 0 10px 70px 0 rgb(103 151 255 / 55%), 0 15px 105px 0 rgb(103 151 255 / 55%);
                    transition: all 0.5s ease 0s;
                    fill: #00b5e6;
                    color: #00b5e6;
                }

        .card-btn {
            font-weight: 900;
            font-size: 22px;
            letter-spacing: 1px;
            line-height: 1.4em;
        }

        svg {
            width: 28px;
            height: 28px;
            margin: 0 12px 0 0;
        }

        .svgcss {
            fill: #00b5e6;
            color: #00b5e6;
        }

        .text-c {
            height: 300px;
            margin-top: 10vh;
        }

        .reveal {
            visibility: hidden;
        }

        .alpha-50 {
            background: rgba(255, 255, 255, 0.5);
        }
    </style>
</head>

<body>
    <a href="#" class="d-none d-md-block">
        <div class="gotop">
        </div>
    </a>
    @*luxy*@
    <div id="luxy">
        <!-- header -->
        <header class="vh-100">
            <div class="container h-100">
                <div class="row align-items-center h-100">
                    <div class="col-md-5">
                        <div class="btn btn-outline-primary fs-2 rounded-pill mb-3" style="background-color: rgba(129, 236, 236, 0.7);">
                            <img src="~/img/看哪科.png" style="width: 10%;" class="me-1" />@Html.ActionLink("看哪一科", "List", "Search")
                        </div>
                        <div class="btn btn-outline-primary fs-2 rounded-pill mb-3" style="background-color: rgba(129, 236, 236, 0.7);">
                            <img src="~/img/門診.png" style="width: 10%;" class="me-1" />@Html.ActionLink("門診掛號", "List", "Outpatient")
                        </div>
                        <div class="btn btn-outline-primary fs-2 rounded-pill mb-3" style="background-color: rgba(129, 236, 236, 0.7);">
                            <img src="~/img/檢驗檢查.png" style="width: 10%;" class="me-1" />@Html.ActionLink("檢驗檢查", "ExamList", "Examination")
                        </div>
                        <div class="btn btn-outline-primary fs-2 rounded-pill mb-3" style="background-color: rgba(129, 236, 236, 0.7);">
                            <img src="~/img/doctor.png" style="width: 10%;" class="me-1" />@Html.ActionLink("回診紀錄", "Return", "Return")
                        </div>
                        <div class="btn btn-outline-primary fs-2 rounded-pill mb-3" style="background-color: rgba(129, 236, 236, 0.7);">
                            <img src="~/img/用藥.png" style="width: 10%;" class="me-1" />@Html.ActionLink("用藥查詢", "List", "Medicine")
                        </div>
                    </div>
                </div>
            </div>
        </header>


        <header class="d-flex justify-content-center align-items-center spacer layer1">
            <div class="text-c d-grid gap-3">
                <h1 class="hidden-text"></h1>
                <h1 class="hidden-text">網頁導覽</h1>
            </div>
        </header>
        <div class="section container-fluid d-flex">
            <div class="row g-0">
                <div class="col-12 col-lg-8 order-lg-2 my-auto">
                    <div class="reveal">
                        <div class="box">
                            <video id="v1" muted playsinline controls autoplay>
                                <source src="/img/home/search.mp4" type="video/mp4" />
                            </video>
                            <video id="v2" class="d-none" muted playsinline controls autoplay>
                                <source src="/img/home/video1.mp4" type="video/mp4" />
                            </video>
                            <video id="v3" class="d-none" muted playsinline controls autoplay>
                                <source src="/img/home/oupatient.mp4" type="video/mp4" />
                            </video>
                            <video id="v4" class="d-none" muted playsinline controls autoplay>
                                <source src="/img/home/examination.mp4" type="video/mp4" />
                            </video>
                            <video id="v5" class="d-none" muted playsinline controls autoplay>
                                <source src="/img/home/search.mp4" type="video/mp4" />
                            </video>
                            <video id="v6" class="d-none" muted playsinline controls autoplay>
                                <source src="/img/home/video4.mp4" type="video/mp4" />
                            </video>
                        </div>
                    </div>
                </div>
                <div class="
              col-6 col-lg-2
              order-lg-1
              d-flex
              justify-content-center
              align-items-center
            ">
                    <ul class="ul-home">
                        <li onclick="videoUrl('v1')">
                            <div class="card-btn me-3">
                                <svg viewBox="0 0 28 28">
                                    <path d="M11,19V9l8,5L11,19z"></path>
                                    <path class="transparent"
                                          d="M14,2c6.62,0,12,5.38,12,12s-5.38,12-12,12S2,20.62,2,14S7.38,2,14,2 M14,0C6.27,0,0,6.27,0,14 c0,7.73,6.27,14,14,14s14-6.27,14-14C28,6.27,21.73,0,14,0L14,0z"></path>
                                </svg>
                                會員系統
                            </div>
                        </li>
                        <li onclick="videoUrl('v2')">
                            <div class="card-btn me-3">
                                <svg viewBox="0 0 28 28">
                                    <path d="M11,19V9l8,5L11,19z"></path>
                                    <path class="transparent"
                                          d="M14,2c6.62,0,12,5.38,12,12s-5.38,12-12,12S2,20.62,2,14S7.38,2,14,2 M14,0C6.27,0,0,6.27,0,14 c0,7.73,6.27,14,14,14s14-6.27,14-14C28,6.27,21.73,0,14,0L14,0z"></path>
                                </svg>
                                看哪一科
                            </div>
                        </li>
                        <li onclick="videoUrl('v3')">
                            <div class="card-btn me-3">
                                <svg viewBox="0 0 28 28">
                                    <path d="M11,19V9l8,5L11,19z"></path>
                                    <path class="transparent"
                                          d="M14,2c6.62,0,12,5.38,12,12s-5.38,12-12,12S2,20.62,2,14S7.38,2,14,2 M14,0C6.27,0,0,6.27,0,14 c0,7.73,6.27,14,14,14s14-6.27,14-14C28,6.27,21.73,0,14,0L14,0z"></path>
                                </svg>
                                門診掛號
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="
              col-6 col-lg-2
              order-lg-3
              d-flex
              justify-content-center
              align-items-center
            ">
                    <ul class="ul-home">
                        <li onclick="videoUrl('v4')">
                            <div class="card-btn me-3">
                                <svg viewBox="0 0 28 28">
                                    <path d="M11,19V9l8,5L11,19z"></path>
                                    <path class="transparent"
                                          d="M14,2c6.62,0,12,5.38,12,12s-5.38,12-12,12S2,20.62,2,14S7.38,2,14,2 M14,0C6.27,0,0,6.27,0,14 c0,7.73,6.27,14,14,14s14-6.27,14-14C28,6.27,21.73,0,14,0L14,0z"></path>
                                </svg>
                                檢驗檢查
                            </div>
                        </li>
                        <li onclick="videoUrl('v5')">
                            <div class="card-btn me-3">
                                <svg viewBox="0 0 28 28">
                                    <path d="M11,19V9l8,5L11,19z"></path>
                                    <path class="transparent"
                                          d="M14,2c6.62,0,12,5.38,12,12s-5.38,12-12,12S2,20.62,2,14S7.38,2,14,2 M14,0C6.27,0,0,6.27,0,14 c0,7.73,6.27,14,14,14s14-6.27,14-14C28,6.27,21.73,0,14,0L14,0z"></path>
                                </svg>
                                我的藥盒
                            </div>
                        </li>
                        <li onclick="videoUrl('v6')">
                            <div class="card-btn me-3">
                                <svg viewBox="0 0 28 28">
                                    <path d="M11,19V9l8,5L11,19z"></path>
                                    <path class="transparent"
                                          d="M14,2c6.62,0,12,5.38,12,12s-5.38,12-12,12S2,20.62,2,14S7.38,2,14,2 M14,0C6.27,0,0,6.27,0,14 c0,7.73,6.27,14,14,14s14-6.27,14-14C28,6.27,21.73,0,14,0L14,0z"></path>
                                </svg>
                                回診紀錄
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="section space"></div>
    </div>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.7.1/gsap.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/luxy.min.js"></script>
    <script src="~/Scripts/HomeIndex.js"></script>
</body>

</html>

prjHosNav/Views/Home/Search.cshtml
@{
    ViewBag.Title = "Search";
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/Search.js"></script>
<style>
    body {
        background-color: #e8fbff;
    }

    .card-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .alpha-50 {
        background: rgba(255, 255, 255, 0.6);
    }

    .text {
        font-size: 14px;
    }

    .item {
        margin-bottom: 18px;
    }

    header {
        height: 300px;
        background-image: url('https://cdn.pixabay.com/photo/2015/05/29/19/17/study-789631_1280.jpg');
        background-repeat: no-repeat;
        background-position: center center;
        background-size: cover;
    }
</style>
<!-- Jumbotron -->

<div id="app">
    <header class="d-flex justify-content-center align-items-center">
        <div class="text-center">
            <div class="card alpha-50">
                <div class="card-body">
                    <h2 class="fw-bold">症狀查詢管理</h2>
                </div>
            </div>
        </div>
    </header>
    <el-card class="box-card">
        <template #header>
            <div class="card-header">
                <span>症狀查詢管理</span>
                <el-button size="small" type="success" data-bs-toggle="modal" data-bs-target="#myModal" @@click="clearTextBox();">新增資料</el-button>
            </div>
        </template>
        <div>
            <el-table :data="tableData"
                      border
                      max-height="1200"
                      :header-cell-style="{
                     'background-color': '#1989fa',
                     'color': '#fff',
                     'font-weight': '400'
                 }">
                style="width: 100%"
                :row-style="tableRowStyle>
                <el-table-column prop="SId"
                                 label="編號"
                                 width="100"
                                 align="center">
                </el-table-column>
                <el-table-column prop="SType"
                                 label="科別"
                                 width="auto"
                                 align="center">
                </el-table-column>
                <el-table-column prop="SDisease"
                                 label="症別"
                                 width="620"
                                 max-height="250">
                </el-table-column>
                <el-table-column prop="SSymptom"
                                 label="症狀"
                                 width="620"
                                 max-height="250">
                </el-table-column>
                <el-table-column label="操作" width="145">
                    <template #default="scope">
                        <el-button size="mini"
                                   type="primary"
                                   @@click="getbyID(scope.row.SId)">編輯</el-button>
                        <el-button size="mini"
                                   type="danger"
                                   @@click.prevent="Delele(scope.row.SId)">删除</el-button>
                    </template>
                </el-table-column>
            </el-table>
        </div>
    </el-card>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="myModalLabel">門診管理</h4>
                    <button type="button" class="close" data-bs-dismiss="modal">×</button>
                </div>
                <div class="modal-body">
                    <el-form>
                        <div class="form-group">
                            <el-divider content-position="left">ID</el-divider>
                            <input type="text" id="SId" class="form-control" disabled="disabled" />
                        </div>
                        <div class="form-group">
                            <el-divider content-position="left">科別</el-divider>
                            <input type="text" id="SType" class="form-control" />
                        </div>
                        <div class="form-group">
                            <el-divider content-position="left">症別</el-divider>
                            <input type="text" id="SDisease" class="form-control" />
                        </div>
                        <div class="form-group">
                            <el-divider content-position="left">症狀</el-divider>
                            <input type="text" id="SSymptom" class="form-control" />
                        </div>
                    </el-form>
                </div>
                <div class="modal-footer">
                    <span class="dialog-footer">
                        <button class="btn btn-outline-primary" round id="btnAdd" onclick="return Add();">新增</button>
                        <button class="btn btn-outline-primary" round id="btnUpdate" style="display:none;" onclick="Update();">更新</button>
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script src="https://unpkg.com/vue@next"></script>
    <link href="~/Content/tailwind.min.css" rel="stylesheet" />
    <script src="//unpkg.com/element-plus"></script>
    <link rel="stylesheet" href="//unpkg.com/element-plus/dist/index.css">
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="~/Scripts/SearchKeyword.js"></script>
}

prjHosNav/Views/Home/outpatient.cshtml
@{
    ViewBag.Title = "outpatient";
}


<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="~/Scripts/outpatient.js"></script>

<style>
    .alpha-50 {
        background: rgba(255, 255, 255, 0.9);
    }

    header {
        height: 300px;
        background-image: url('https://cdn.pixabay.com/photo/2015/05/29/19/17/study-789631_1280.jpg');
        background-repeat: no-repeat;
        background-position: center center;
        background-size: cover;
    }
</style>
<!-- Jumbotron -->
<header class="d-flex justify-content-center align-items-center">
    <div class="text-center">
        <div class="card alpha-50">
            <div class="card-body">
                <h4 class="fw-bold">門診管理</h4>              
            </div>
        </div>
    </div>
</header>

<!--Table-->
<div style="background-color:#E8FBFF;" class="row justify-content-center">
    <div class="my-5 bg-light w-75 shadow" style="border-radius:20px">
        <div class="d-flex align-items-center px-3 py-4 ">
            <h3 class="fw-bold me-auto">門診列表</h3>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary mx-3" data-bs-toggle="modal" data-bs-target="#myModal" onclick="clearTextBox();">新增門診</button>
        </div>
        <div class="table-responsive">
            <table class="table table-bordered table-hover text-center">
                <thead>
                    <tr>
                        <th scope="col" nowrap>
                            門診ID
                        </th>
                        <th scope="col" nowrap>
                            門診名
                        </th>
                        <th scope="col" nowrap>
                            醫師名
                        </th>
                        <th scope="col">
                            操作
                        </th>
                    </tr>
                </thead>
                <tbody class="tbody"></tbody>
            </table>
        </div>
    </div>
</div>

<!--Modal-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-bs-dismiss="modal">×</button>
                <h4 class="modal-title" id="myModalLabel">門診管理</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="oid">ID</label>
                        <input type="text" class="form-control" id="oid" disabled="disabled" />
                    </div>
                    <div class="form-group">
                        <label for="oName">門診名</label>
                        <input type="text" class="form-control" id="oName" />
                    </div>
                    <div class="form-group">
                        <label for="oDoctor">醫師名</label>
                        <input type="text" class="form-control" id="oDoctor" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnAdd" onclick="return Add();">Add</button>
                <button type="button" class="btn btn-success" id="btnUpdate" style="display:none;" onclick="Update();">Update</button>
                <button type="button" class="btn btn-default" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>